import { mediaComments } from './comments.js'; 
import './script.js';
import './product-cards.js'; 
import './homework-5.js'; 
import './homework-7.js'; 
import './homework-8.js'; 
import './footer.js'; 
import './homework-10.js';
import './Form.js';
import './Modal.js'; 